### ISSUE TITLE
App crashes when clicking on profile

### ISSUE THREAD

**Issue by Maxr1998** [metabrainz/listenbrainz-android#483]
During the current ListenBrainz outage and shortly after setting up the app (not logged in yet), clicking on "Profile" in the bottom sheet crashes the app.

<details>
<summary>logs</summary>

```
E AndroidRuntime : FATAL EXCEPTION: main
Process: org.listenbrainz.android, PID: 31195
java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/profile/ } cannot be found in the navigation graph ComposeNavGraph(0x0) startDestination={Destination(0x78d736ab) route=feed}
	at androidx.navigation.NavController.navigate(NavController.kt:1819)
	at androidx.navigation.NavController.navigate(NavController.kt:2225)
	at androidx.navigation.NavController.navigate$default(NavController.kt:2220)
	at androidx.navigation.NavController.navigate(NavController.kt:2205)
	at org.listenbrainz.android.ui.navigation.BottomNavigationBarKt$BottomNavigationBar$1$1$1$1.invokeSuspend(BottomNavigationBar.kt:88)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeCollector.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@ac1ab78, androidx.compose.runtime.BroadcastFrameClock@d84c251, StandaloneCoroutine{Cancelling}@619ab6, AndroidUiDispatcher@57683b7]
```
</details>

**Comment by 07jasjeet** [comment]
@Maxr1998 Thanks for reporting, will be fixed in next release!
